(TeX-add-style-hook
 "thesis"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "11pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("url" "hyphens") ("inputenc" "utf8") ("fontenc" "T1") ("ulem" "normalem") ("hyperref" "colorlinks=true" "citecolor=BrickRed" "linkcolor=BrickRed" "urlcolor=BrickRed") ("datetime" "level") ("biblatex" "autocite=plain" "backend=biber" "doi=true" "url=true" "hyperref=true" "uniquename=false" "maxbibnames=99" "maxcitenames=2" "sortcites=true" "style=authoryear-comp") ("quattrocento" "sf" "scaled=0.9") ("sourcecodepro" "oldstyle" "scale=0.7") ("xcolor" "hyperref" "x11names") ("tocbibind" "nottoc") ("geometry" "margin=1.25in")))
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-environments-local "minted")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (TeX-run-style-hooks
    "latex2e"
    "bibliography-mimosis"
    "article"
    "art11"
    "url"
    "float"
    "inputenc"
    "fontenc"
    "graphicx"
    "grffile"
    "longtable"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "amssymb"
    "capt-of"
    "hyperref"
    "etoolbox"
    "bookmark"
    "bbding"
    "hyphenat"
    "datetime"
    "biblatex"
    "quattrocento"
    "sourcecodepro"
    "floatrow"
    "listings"
    "minted"
    "scrhack"
    "xcolor"
    "physics"
    "cases"
    "tikz"
    "tocbibind"
    "geometry"
    "subfigure"
    "pdflscape")
   (TeX-add-symbols
    '("tikzremember" 1)
    '("thesisnoop" 1)
    '("showacknow" 1)
    '("acknow" 1)
    '("showmatmethods" 1)
    '("matmethods" 1)
    '("dropcap" 1)
    "ThesisTitle"
    "ThesisSubTitle"
    "FormattedThesisDefenseDate"
    "FormattedAuthorDateOfBirth"
    "FormattedThesisDefenseTime"
    "AuthorShortName"
    "AuthorFullName"
    "AuthorPlaceOfBirth"
    "ThesisISBN"
    "signed")
   (LaTeX-add-labels
    "sec:orgf47f5cc"
    "sec:org037c703"
    "sec:orgaa0eec2"
    "sec:org604327e"
    "larmor"
    "orgd61baeb"
    "sec:org04c7a17"
    "sec:orgfe6f90f"
    "sec:org42eb62d"
    "eq:totalenergy"
    "eq:externaleZpotential"
    "sec:orgfd69196"
    "sec:org089ffcc"
    "sec:orgf03b192"
    "sec:org94baf7d"
    "eq:dftvarprinciple"
    "eq:hks_functional"
    "sec:org9b70d94"
    "sec:org0599dbb"
    "sec:org07582ea"
    "sec:org2d1a0e5"
    "sec:orgcf68d25"
    "sec:org0c4d771"
    "eq:second_order_hks_functional"
    "sec:org44f0e84"
    "sec:org3526230"
    "sec:orgc0ead5f"
    "org476e890"
    "sec:orga80737f"
    "sec:org6ef0439"
    "sec:orge836f71"
    "org0919e36"
    "tab:orgf0396e1"
    "sec:org4012924"
    "sec:org52c87e5"
    "sec:org1c8ef47"
    "sec:org7ee6a5a"
    "sec:org3935723"
    "sec:org6afe6b6"
    "sec:org2e6bec2"
    "sec:orgbc546f1"
    "sec:org74d47d3"
    "fuderpicture"
    "sec:org5e1b108"
    "sec:orga615247"
    "fig:dislocationschematics"
    "sampledpositions"
    "fig:peierlspot"
    "eq:peierlspot"
    "sec:org753edcb"
    "eq:excessenergy"
    "sec:orgf0402cc"
    "sec:org0a55f9b"
    "sec:carbon_concentration"
    "eq:cd"
    "sec:orga5d2e52"
    "sec:ltmodelintro"
    "eq:line-tension"
    "sec:org276c0f0"
    "sec:smoothsitemapping"
    "eq:maxwellboltzmann_conc"
    "sec:org49a2734"
    "sec:concentration_statistics_discussion"
    "sec:org4856e98"
    "sec:orgfc87037"
    "tab:peierlspot"
    "hardsplittransition"
    "sec:org3a83b78"
    "lnrdep"
    "sec:orgad2d7e7"
    "sec:fec_binding"
    "decayrelations"
    "easybindingenergydist"
    "hardbindingenergydist"
    "tab:bindingenergies"
    "sec:org2fa09e5"
    "cdhardeasy"
    "sec:org3d13e26"
    "sec:ltmodel"
    "sec:orgdce83da"
    "distancedep"
    "lorentzianfit"
    "sec:org4b62651"
    "lineshape"
    "easyeasytransition"
    "kink-pair_formation_enthalpy_pure"
    "sec:org97879fa"
    "fig:alllineshapes"
    "fig:pathwaysinglec"
    "kinkpairstress"
    "wignercorrection"
    "sec:org51deca0"
    "sec:kink-pair_nucleation_rate"
    "eq:jumprate"
    "eq:kinkrate"
    "eq:enhancementfactor"
    "rateenhancement"
    "sec:org35a55ec"
    "sec:org51a151f"
    "sec:org23516df"
    "fig:straighttbequib"
    "fig:straighttbstatic"
    "sec:org05549fe"
    "sec:kinkpairformationequib"
    "fig:kinkpairequib"
    "fig:kpequibpath"
    "eqkinkrate"
    "sec:orgdb4d727"
    "sec:orgb57211d"
    "sec:org34a622e"
    "sec:org77a27e0"
    "sec:orge178851"
    "sec:org74cd325"
    "eq:discrete_diffusion_model"
    "eq:ivo_diffusion_model"
    "sec:org5adb164"
    "sec:discussion"
    "sec:orgf0454ed"
    "sec:orgfa459b6"
    "sec:org6e5f268"
    "sec:org1e7b00d"
    "sec:Ainteractionenergy"
    "sec:orgc3a426d"
    "sec:zeropointenergy"
    "sec:org614f22f"
    "fig:kpoccupancies"
    "sec:org525c467"
    "org29218d5"
    "sec:org59bd8d6"
    "sec:org0e858d8"
    "sec:orgece04b8"
    "sec:orgdbf6332"
    "sec:org2cb5aa4"
    "sec:orga6d62e3")
   (LaTeX-add-environments
    '("aquote" 1)
    "abstract")
   (LaTeX-add-bibliographies
    "../bibliography/zoteroLibrary.bib"
    "../bibliography/org-refs"
    "bibliography/org-refs")
   (LaTeX-add-saveboxes
    "mybox"))
 :latex)

