#+TITLE: SKF Internship: Things to do
#+AUTHOR: Tigany Zarrouk


* Tasks



** TODO Read Itakura
** TODO Determine Calculations
   DEADLINE: <2019-11-21 Thu>
   
   - What needs to be calculated for the construction of a Kinetic Monte Carlo model?

   - How have the calculations by Wang et al changed anything?


*** TODO 
** TODO Project outline
   DEADLINE: <2019-11-22 Fri>
   
   Create Gantt chart for the project. 


    The open questions in terms of mechanisms are:

    - Can dislocations carry carbon when they move?

    - Do temper carbides dissolve with rolling contact fatigue? Or do
      they grow?



*** TODO Details of the context of the project. 

**** Initial microstructure of bearing steel
     
     - Machined bearings are heat treated to produce a *martensitic* microstructure.
     - This is subsequently tempered.
     - In the martensitic and tempered condition, bearing steel consists of at least four different phases.
       1) Retained *austenite*
       2) A tempered *martensitic matrix*
       3) Tempered *transition carbides & cementite*
       4) Dispersed residual *cementite*
	  * This has a structure of $M_3C$ where M can be Mn/Cr.

     - During /Austenisation/ a fraction of the spheroidised cementite dissolves and leads to a carbon enrichment of the austenite. 


***** Austenite

      - This is fcc structure iron ($\gamma$ phase).
      - Generally a solid solution of iron and alloying elements. 

      Austenitization means to heat the iron, iron-based metal, or steel to a temperature at which it changes crystal structure from ferrite to austenite.[3] The more open structure of the austenite is then able to absorb carbon from the iron-carbides in carbon steel. An incomplete initial austenitization can leave undissolved carbides in the matrix.

For some iron metals, iron-based metals, and steels, the presence of carbides may occur during the austenitization step. The term commonly used for this is two-phase austenitization

***** Martensite
      - A very hard phase of iron
      - Formed by quenching from /austenite/ (fcc iron) at such a high rate such that the carbon has no time to diffuse out of the microstructure to form /cementite/.
      - This causes the fcc to transform to the highly strained body-centred tetragonal phase of /martensite/.
      - It is supersaturated with carbon.
      - The shear deformations that result form a /large number of dislocations/, which is the *primary mechanism* for the strengthening of steels.
      
***** Cementite
      - This is the name for the iron carbide Fe_3C
      - It is hard and brittle

***** Ferrite
      This is just bcc iron ($\alpha$ phase)


**** Review of the problem
     - With a bearing on a raceway one can expect a /Hertzian/ distribution of the stress.
     - This leads to a large degree of stress on the /subsurface/ of the raceway.
     - It has been seen in cross sections of the bearing raceway, with an increase in the number of fatigue cycles, after etching, dark and light etched regions start to develop.
     - The light regions correspond to the normal microstructure.
     - Dark regions seem to correspond to regions of high /von Mises/ stress from the Hertzian distribution of the stress.
       - These are called /Dark Etched Regions/ (DERs)
     - Within the DERs there are /white etched bands/ (WEBs).

     - DERs are dark because there is more scattering of the light from the microscope so this implies a larger roughness

     - It is not clear what the microstructure of the dark regions are. Nor what the white etched bands are.

     - It it thought that the development of these regions is due to carbon diffusion and migration.
     - I am not sure how carbon diffusion causes a change in the color of the image.
     - But basically there are a couple of theories into the carbon migration.


**** Structure of DERs
     - DERs are dark because there is more scattering of the light from the microscope so this implies a larger roughness
     - The material is more brittle and hard (but this depends on temperature)
       - Some results have shown that the hardness is similar or that the hardness decreases/increases. There is not a consensus.

     - DER is accomompanied by development of compressive residual stresses.
       - X-ray diffraction has results in line broadening (a broader peak) with harder materials so FWHM is less. 
       - Peak is narrower and higher in DER region so FWHM is higher. 




**** Cambridge's theory

     - The theory is that essentially there are grains of martensite.
     - Within these grains there are carbide precipitates of different types.
     - It is thought that dislocations move in a cottrell atmosphere of carbon and then they deposit it into the precipitates.
     - They tried to validate this claim by looking at atom probe tomography of a portion of the sample.
     - They see near regions of large amounts of carbon, there are regions of decreased carbon content.
     - They try to relate these regions of a high carbon concentration to different forms of carbide but there is debate as to whether the resolution of the APT results to actually determine with certainty what the actual stochiometry of the precipitates are.

       
***** Qualms 

      1) Is it valid to say that the dislocations actually deposit carbon into the carbides?
	 * Is there a segregation energy from dislocations to these carbide regions?
	 * Predrag is looking at this with some interatomic potentials to see if there is favourable segregation of C from dislocation to precipitate. 
	 * Do temper carbides dissolve with rolling contact fatigue?
      2) Experimentalists don't seem to have seen any carbides. They don't think that this mechanism is likely.
      3) It is thought that these carbide precipitates dissolve in the dark region. 
    



**** SKF Theory

     - Think that carbon drags along the cottrell atmosphere with the dislocation.
     - This causes carbon migration.
     - Might also be possible that edge dislocations, due to their high mobility diffuse carbon. 
     - There might also be pipe diffusion of the C down the dislocation line. 
       - This is what the engineers really like
       - Essentially pipe diffusion is where (say with an edge dislocation) a vacancy and an "interstitial" pair are created where the interstitial moves downwards (negative climb direction)
       - If this pair don't annihilate then diffusion takes place and this interstitial will diffuse down the dislocation line


**** Notes from Predrag
      
     - Given a diffusion equation of the form 

       \[ \frac{\partial c}{\partial t} = \nabla ( D \nabla c ) - \nabla \cdot (\mathbf{v}c) + R\]

     - Where c is the variable of interest (say concentration)
     - D is the diffusion coefficient (diffusivity)
     - $\mathbf{v}$ is a velocity field that the quantity is moving with.
       - e.g In /advection/ then $c$ is the concentration of salt in a river and $\mathbf{v}$ would be the velocity of the water as a function of time and location.
       - This is a quantity that is /driving the diffusion/. 
     - $R$ Describes sources and sinks of the quantity. 

	
     - In relation to diffusion of carbon, we can say that $c$ is the concentration of carbon.
     - In general the diffusion term (the first term) will be quite small.
     - The velocity term makes the larger contributions. 

     /What is this velocity term composed of in terms of dislocations and carbon diffusion?/

     - One can think of this velocity term as being decomposed into several parts.
     - In a paper by Sadeghi? They relate this velocity term to something of the form 

       \[ \mathvf{v} = \frac{D}{k_B T} W \]

     - Where $W$ is the /work due to dissipation of plastic strain/ defined as (maybe):
       \[ W = \int \sigma \varepsilon^p d^3r \]

     - But one can also think about this in the case of a solute interacting with the strain field of a dislocation. 

       \[ \mathvf{v} = \frac{D}{k_B T} \nabla ( P \Omega) \]

     - Where $\Omega$ is the /misfit volume/.
     - $P$ is the trace of the stress tensor

       



***  Relevant Articles
    Here is the article where the first model is described:
    
    http://dx.doi.org/10.1016/j.actamat.2017.08.005
    [[file:papers/Strain-induced_Martensite_Decay_in_Bearing_Steels_under_Rolling_Contact_Fatigue_Modelling_and_Atomic-scale_Characterisation.pdf]]
    
    And here the second model:

    http://www.tandfonline.com/doi/abs/10.1080/10402004.2012.754073

    [[file:papers/warhadpande2013.pdf]]


    http://www.tandfonline.com/doi/abs/10.1080/10402004.2013.847999

    [[file:papers/warhadpande2013-1.pdf]]
 

    The open questions in terms of mechanisms are:

    - Can dislocations carry carbon when they move?

    - Do temper carbides dissolve with rolling contact fatigue? or do they grow?

 
    
** TODO Create Presentation 
   DEADLINE: <2019-11-25 Mon>
   
   - Make outline of presentaton
   - Tailor it for Eric Vegter and other members of group.
   - Show why this project is important
     - Put in things about how carbon migration is important
     - Check the new proposal
     - Fundamental interactions between C and dislocations. 

** TODO Generate Cells for Calculations
   SCHEDULED: <2019-11-25 Mon>
    Once calculations necessary have been determined I can start generating files that generate dislocations. 
    
    
    - Ask Luke if Hexagonal cells are generally better or not?
    - How does he simulate kinks?
    - Read Luke's Thesis
