#+Author: Tigany Zarrouk
#+Title: Pure Ti fitting

* Plan                                                      :noexport:ignore:
   - [ ] Introduction on fitting
     - Use Luke's paper on overleaf [[https://www.overleaf.com/project/5d36c0f2ee8eac35ddeb27a1]]
     - Use Luke's Thesis
     - Use Dimitar's thesis
   - [ ] Titanium model fitting
     - Fitting data
     - Comparison beween d and sd models
     - Phonon spectra, heat data, phase information and stability.
     - Pure Titanium dislocations

* Fitting a titanium tight-binding model
  \label{ch:ti_fitting}
** Introduction (What, how, where, when, why?)
   Fitted canonical d titanium model such that we could have a better
   description of titanium within a tight-binding framework. Empirical
   potential are not accurate enough to describe the intricacies of the
   titanium structure.

** Fitting

   The overlap integrals were chosen to have a simple exponential
   distance dependence, as initially formulated by Ducastelle,
   cite:Ducastelle1970c and Allan cite:Allan1976. This form was
   originally motivated by an approximation to the density of states,
   of which the form was taken to be a Gaussian fitted to the
   second-moment of the distribution cite:Spanjaard1984. Analysis of
   the hybridisation of $d$ states with nearly-free electron states in
   transition metals gives rise to $d$-band resonances, which suggest a
   fifth-degree power law distance dependence of d-orbitals for the
   matrix elements
   cite:Heine1967,Heine1980,Andersen1985,Harrison1989,Pettifor1995. However, it has
   not been shown that a power-law dependence exhibits better
   transerability over a simple exponential dependence
   cite:Skinner1991,Paxton2010. Many power-law models have not
   fared well in predicting data outside of their fitting range
   cite:Paxton1987,Paxton1989,Girshick1998a,Trinkle2006,Ferrari2019a. Furthermore,
   exponentials do not have large first or second derivatives compared
   to power laws when modified by the cutoff function, which
   complicates fitting for elastic properties, and would provide
   erroneous forces
   cite:Pashov2012. Transferability has been consistently
   shown for the iron tight-binding model created by Paxton and
   Elsässer cite:Paxton2010, which a more flexible exponential
   dependence. Their model predicts data well outside of their fitting
   range: non-degenerate dislocation core structures found in the bcc
   phase cite:Simpsonb,Simpson2020, phonons and vacancy-formation
   energies. In addition, the Fe-Fe interactions have been shown
   suitable when incorporated with Fe-H/Fe-C interactions, to describe
   of hydrides and carbides cite:Paxton2010,Paxton2013.

   # Canonical band theory cite:Andersen1985,Paxton2009a suggests that the bond integrals are in the
   # ratio
   # \[
   # \label{eq:canonical_band_ratio}
   # dd\sigma:  dd\pi:  dd\delta = -6:4:-1.
   # \]
   # These ratios are only applicable to the fifth-order power law
   # dependence of the bond integrals, as there is no characteristic
   # $d$-orbital radius from which to compare the ratios. It has been
   # shown that non-orthogonal models of titanium, which have been
   # subsequently orthogonalised to a $d$-band only model, have canonical
   # ratios which deviate largely from canonical band theory; in the case
   # of Urban /et al./ the ratio turned out to be $dd\sigma: dd\pi:
   # dd\delta = -4.3 : 3.6 : -1$, in which the ordering of the ratio
   # magnitudes changed cite:Urban2011.

   # To obtain better fitting results, these ratios were allowed to vary
   # from those found from canonical band theory. This is standard
   # practice in other models . Non-orthogonal models
   # of titanium, which have been subsequently orthogonalised to a
   # $d$-band only model, have canonical ratios which deviate largely from
   # canonical band theory; in the case of Urban /et al./ the ratio
   # turned out to be $dd\sigma: dd\pi: dd\delta = -2.7 : 6.4 : -1$,
   # in which the ordering of the ratio magnitudes changed
   # cite:Urban2011. We do not allow the ratios to deviate by more than
   # 20% in our fitting.
   # # WHY??-


   The bond integrals and pair potential ranges were chosen to start
   decaying to zero by a multiplicative polynomial between first and
   second neighbours in the hcp structure, going to zero between the
   second and third-neighbours. It was verified that the cutoffs were
   not close to neighbour shells found in titanium
   polymorphs, such that in future simulations, there would be no large
   and sudden forces arising from the inclusion of extra neighbours
   upon deformation. A multiplicative cutoff type was preferred over
   augmentative as it has been shown mitigate the effect of large
   second-derivatives, which would cause difficulty in replicating
   experimental elastic constants and phonon dispersion
   cite:Pashov2012.

   In fitting, it was found that having only first-neighbour
   interactions, did not give desirable properties for the hcp phase:
   elastic constants which resulted in negative Cauchy pressures and a
   poor description of the energy difference between titanium
   polymorphs. Increasing the range of the interactions to
   second-neighbours resulted in more favourable results.


   The form of the pair potential was chosen to be simple sum of two
   exponentials and a rapidly decaying power law term. The exponentials,
   which have one large positive term, and a smaller negative term,
   contribute the most over the range of interaction, with the power
   law chosen to only increase the repulsion at smaller distances. The
   addition of this power law gave more desirable gamma surface
   energies more reminiscent of DFT. This will be discussed in section
   *SECTION LABEL*. The resultant pair potential was highly repulsive
   at short distances, yet became slightly
   attractive at larger distances. This allowed for one to
   approximately account for attractive effect of $sd$ hybridisation
   in this simple $d$-orbital only model, as done
   in previous exclusively $d$-orbital tight-binding models for
   titanium cite:Girshick1998a. Even though hybridisation is
   not strictly pairwise in character, we did not deem it necessary at
   this time to complicate matters further.


   # Insert table for the parameters
   # d-band model
   # fdd=0.1958363809 qdds=0.5591275855 qddp=0.5690351902 qddd=0.7745947522 b0=58.0906936439 p0=1.2185323579 b1=-3.2299188646 p1=0.6862915307 b2=593519.1134129359 m2=-11.5000000000 p2=0.0000000000 ndt=2.0000000000 cr1=-6.0000000000 cr2=3.0474400934 cr3=-1.2317472193 r1dd=6.5000000000 rcdd=10.0000000000 rmaxhm=10.1000000000 npar=18

   # sd model
   # fdd=0.2180620493 qdds=0.6040045421 qddp=0.6169684817 qddd=0.7700371748 b0=62.9010414470 p0=1.1762055161 m0=0.0000000000 b1=-3.0294300785 p1=0.6180563234 b2=0.0000000000 p2=0.0000000000 m2=0.0000000000 ndt=2.0000000000 cr1=-6.0312481443 cr2=4.0191710557 fss=-0.1500000000 qss=0.3700000000 fsds=-0.0636998339 qsds=0.3392893716 esti=-0.2100000000 edti=0.0800000000 r1dd=6.5000000000 rcdd=10.0000000000 cr3=-1.0000000000 rmaxhm=10.1000000000


   # Insert figure for the bond integrals and the pair potential.
   # > Probably good to compare the bond integrals of the sd model,
   # > to the d model
   # > Do I use the model fitted to the TiH/TiO2 things?
   # > Plotting found in [[file:~/Documents/ti/plot_bond_integrals/]]

   #+BEGIN_EXPORT latex
     \begin{figure}[H]
       \begin{center}
         \includegraphics[width=\textwidth]{pictures/sd-d_bond_integrals_together.png}
         \caption[Bond integrals of both $d$ and $sd$ titanium tight-binding models.] {Bond integrals of both $d$ and $sd$ titanium tight-binding models. First and second derivatives shown to demonstrate that there are no abberations when the bond integrals decay to zero between $r_1$ and $r_c$.} %square is table contents, curly is in the chapter
         \label{fig:d_sd_bond_integrals}
       \end{center}
     \end{figure}
   #+END_EXPORT

   # Regularization is generally used so parameters dont become
   # ridiculous and so it stops overfitting
   # [[https://towardsdatascience.com/intuitions-on-l1-and-l2-regularisation-235f2db4c261]]

   The bond integrals and pair potential were fitted to reproduce DFT
   and empirical data, as detailed in table *INSERT TABLE REF*.
   An objective function was defined as

   #+BEGIN_EXPORT latex
     \begin{equation}
       E(\mathbf{x}) = \sum_i
       w_i(f_i(\mathbf{x}) - \hat{f}_i (\mathbf{x}))^2 + \left(     \alpha
       ||\mathbf{x}||_2 + (1-\alpha) || \mathbf{x} ||_1 \right),
       \label{eq:objective_function}
     \end{equation}
   #+END_EXPORT

   where $\mathbf{x}$ is a vector of input parameters,
   $f_i(\mathbf{x})$ are quantities calculated from the input
   parameters and $\hat{f}_i(\mathbf{x})$ are the respective target
   quantities from DFT or empirical data. $w_i$ are the weights for
   each quantity. Quantities of higher importance, such as lattice and
   elastic constants, were given larger weights in the objective
   function, as such, the optimiser would have a preference to
   minimise these quantities. To mitigate the overfitting of
   parameters (and to dissuade parameters from becoming too large), an
   Elastic Net regularisation term was added to the objective
   function, the final term in equation [[eqref:eq:objective_function]],
   which consists of the L1 and L2 of the input parameter vector
   $\mathbf{x}$. The L2 norm acts as a penalty for large input
   parameters, and the L1 norm gives further penalties, but has the
   added benefit of allowing sparsity of the parameters during
   optimisation: it allows redundant parameters, say in the pair
   potential, to go to zero cite:Hastie2009,Bishop2006.

   The objective function was minimised within pre-defined constraints
   by use of the the CMA-ES (Covariance Matrix Adaptation-Evolution
   Strategy) algorithm, using the python implementation by Hansen
   cite:hansen2019pycma. Parameters put into the CMA-ES algorithm were
   first transformed to have similar sensitivities with respect to the
   bounds in which they are sought cite:Hansen2016. This allows for
   the initial assumption of the CMA-ES algorithm, that the covariance
   matrix is unity, to be more readily satisfied, and a better
   conditioned parameter space for the CMA-ES
   cite:Jastrebski2006,Hansen2011. This mitigates premature
   convergence. Parameters were consequently transformed back,
   allowing for evaluation of the objective function and loss
   function, of which the latter was consequently fed into the CMA-ES
   optimiser.


   The data used to fit to was a mix of DFT and empirical data. Great
   importance was given to the hcp lattice parameter, and the
   structural energy differences between the titanium polymorphs, all
   of which were compared to GGA LMTO calculations using the questaal
   suite cite:Pashov2020. Bandwidths at the high symmetry points of
   the hcp bands were used as targets, and calculated from DFT by
   ascertaining bands of dominant $d$ character and taking the
   difference between the highest and lowest eigenvalues. $d$
   character was determined by by decomposition of the eigenvector
   norm by summation over corresponding orbital subsets, similar to a
   Mulliken analysis.

   To hasten the fitting of parameters, if a set of parameters
   produced a quantity which was out of an acceptable range, then the
   objective function would immediately cease and submit a large value
   to the objective function, dissuading the optimisation algorithm
   from searching close to that area in parameter space.

   All calculations for each of the phases, bar the $4h$ and $6h$
   phases, were done with a k-mesh of
   $30\times 30\times 30$. The $4h$ and $6h$ phases had their k-points
   along the $c$-axis reduced by 2 and 4 times respectively.
   Optimal lattice parameters were found by minimisation of the cohesive energy
   with respect to the given lattice constant(s) using a Nelder-Mead
   algorithm. Elastic constants were determined by the dependence of
   the energy with respect to particular strains of the structure, about the optimal
   lattice parameters cite:Fast1995,Girshick1998. A fifth-order
   polynomial was fitted, to each of these dependences, and the
   curvature extracted from the minimum, from which the constants can
   be calculated.   The bulk modulus was determined similarly, but from
   the dependence of the cohesive energy with volume.

   When evaluating the $C_{11}$, $C_{12}$ and $C_{66}$, it was
   necessary to fully relax the structure (without modifying the
   volume) at each strain, prior to polynomial fitting. This is due to
   the fact that in a strained hcp lattice there are internal degrees
   of freedom that are not accounted for when applying a homogeneous
   strain cite:Clouet2012. One can also calculate the change to these
   three constants by calculating internal elastic constants, as in
   the paper by Cousins cite:Cousins1979. Two of these calculated internal
   elastic constants (which modify all of the aforementioned elastic
   constants) are related to two phonon frequencies of the optical
   branches at the $\Gamma$-point.


   Results from the first stages of fitting found that soft modes
   would appear in the phonon spectra for omega and hcp phases,
   despite their structural stability indicated by their elastic
   constants cite:Wallace1998,Nye1984. As such it was necessary to calculate the phonon density
   of states during objective function evaluation, to verify there
   were no negative densities, as represented in the ~phonopy~ code
   cite:Togo2015.

   The parameters obtained are shown in table ref:table:titanium_objective_function

   # Insert figure for the bands compared to DFT
   # > Use the band plot of dimitar for all the coloured bands?

   # Insert figure for the table of properties.

   # Use multi row and multi column for better formatting of the table.
   #+BEGIN_EXPORT latex
     \begin{table}[H]
       \centering
       \begin{tabular}{lccc}
          Quantity  &    $d$ model &   $sd$ model &       Target \\
          \hline
         $a_{\text{hcp}}$ [bohr]&   5.585 &   5.674 &   5.577 \\
         $c/a(\text{hcp})$ &   1.584 &   1.586 &   1.587 \\
          $a_{\text{omega}}$ [bohr] &   8.935 &   9.039 &   8.733 \\
          $c_{\text{omega}}$ [bohr] &   5.387 &   5.486 &   5.323 \\
          $a_{\text{4h}}   $ [bohr] &   5.576 &   5.681 &   5.563 \\
          $c_{\text{4h}}   $ [bohr] &  18.098 &  18.328 &  17.759 \\
          $a_{\text{6h}}   $ [bohr] &   5.574 &   5.676 &   5.546 \\
          $c_{\text{6h}}   $ [bohr] &  27.184 &  27.579 &  26.771 \\
          $a_{\text{bcc}}  $ [bohr] &   6.201 &   6.201 &   6.179 \\
         $a_{\text{fcc}}  $  [bohr] &   7.873 &   8.013 &   7.887 \\
         \hline
          $E(\omega) - E( \text{hcp})  [\unit{\milli\rydberg}]$ &   0.588 &  -0.357 &  -0.633 \\
          $E(4h)- E(\text{hcp}) $ [\unit{\milli\rydberg}] &   1.580 &   1.663 &   3.172 \\
          $E(6h)- E(\text{hcp}) $ [\unit{\milli\rydberg}] &   2.483 &   2.400 &   3.720 \\
          $E(\text{bcc}) - E( \text{hcp})  $ [\unit{\milli\rydberg}] &   5.351 &   7.958 &   7.635 \\
          $E(\text{fcc}) - E( \text{hcp})  $ [\unit{\milli\rydberg}] &   3.780 &   3.825 &   4.519 \\
         \hline
          $C_{11}$ [GPa] & 171.6 & 167.3 & 176.1 \\
          $C_{33}$ [GPa] & 198.9 & 205.2 & 190.5 \\
          $C_{44}$ [GPa] &  47.4 &  46.6 &  50.8 \\
          $C_{12}$ [GPa] &  94.7 &  96.7 &  86.9 \\
          $C_{13}$ [GPa] &  61.2 &  60.9 &  68.3 \\
         \hline
         hcp bandwidth $\Gamma$ [eV] &   3.69 &   8.90 &   5.87 \\
         hcp bandwidth $K$ [eV] &   4.65 &   4.79 &   4.97 \\
         hcp bandwidth $M$ [eV] &   5.19 &   5.54 &   7.78 \\
         hcp bandwidth $L$ [eV] &   4.21 &   5.43 &   6.34 \\
         hcp bandwidth $H$ [eV] &   3.54 &   4.85 &   9.70 \\
         \hline
         $E_{\text{prismatic}$ fault  &         99.0 &        110.4 & 220.0 \\
         $E_{\text{basal}$ fault &              &        208.9 &              \\
         $E_{\text{pyramidal I}$ fault   &              &        154.6 &              \\

       \end{tabular}
       \caption[Table of the titanium objective function values compared to DFT target data.] {Table of the titanium objective function values compared to DFT target data. The hcp lattice parameter, and the structural energy differences between titanium polymorphs were given large weights in the objective function. \label{table:titanium_objective_function}}
       \end{table}
   #+END_EXPORT


   # #+BEGIN_EXPORT latex
   #   \qty{98.953}{\milli\joules\per\metre\squared} \langle {} \rangle \mu
   # #+END_EXPORT





    ----------     E_prismatic_fault     -----------

    | tbe: |  98.953 | mJ/m^2 |                |
    | DFT: | 250.000 | mJ/m^2 | [Benoit  2012] |
    | DFT: | 233.000 | mJ/m^2 | [Ackland 1999] |


    ----------     E_Basal_fault I2     -----------

    | tbe: | 211.658 | mJ/m^2 |                 |
    | DFT: | 260.000 | mJ/m^2 | [Benoit  2012]  |

   
   # sd 44.26737066
   #   13.17181191

   # The motivaton behind this starting
   # point was such that one could use the work of Legrand
   # cite:Legrand1984 which exhibited dislocation core structures and
   # stacking fault energies which were more physical than previous
   # tight-binding models cite:Trinkle2006a.

   # To fit the canonical-d tight-binding model for titanium, we firstly
   # determined the region of parameter space in which


*** Notes:                                                         :noexport:

**** Structure
     - What is the form of the bond integrals and why?
       - Bond integrals
       - Pair potential
	 - Lack of embedding term for hybridisation, why?
	 - Perhaps use Pettifor's argument for the addition of the
           attractive term in the pair potential as an argument for
           hybridisation?
	 - This does not work for the form of the sd titanium model.
     - What is the fitting data?
       - Is this good data to use?
       - What is the motivation?
     - What algorithm was used to fit and why?



**** General Notes
   
     - The exponential bond integral comes from the density of states
       being assumed to be
     - Could the parameterisation be enhanced by environmentally-dependent
     bond integrals?

** sd fitting: Including hybridisation

   We included s orbitals such that one could more readily model the
   Ti$^{4+}$ oxidation state of the Ti ion, which would give a more
   physical representation of titanium ions in quantum electrochemistry
   calculations.
