#+Author: Tigany Zarrouk
#+Title: Pure Ti fitting
#+LATEX_HEADER: \usepackage[hyperref,x11names]{xcolor}
#+LATEX_HEADER: \usepackage{physics}
#+LATEX_HEADER: \usepackage{cases}
#+LATEX_HEADER: \graphicspath{ {./} }
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{arrows,plotmarks,calc,positioning,fit}
#+LATEX_HEADER: \usetikzlibrary{shapes.geometric, decorations.pathmorphing, patterns, backgrounds}
#+LATEX_HEADER: \newcommand{\tikzremember}[1]{{  \tikz[remember picture,overlay]{\node (#1) at (0,11pt) { };}}}
#+LATEX_HEADER: \tikzset{snake it/.style={decorate, decoration=snake}}
#+LATEX_HEADER: \usepackage[nottoc]{tocbibind}
#+LATEX_HEADER: \usepackage{mimosis}

   - [ ] Introduction on fitting
     - Use Luke's paper on overleaf [[https://www.overleaf.com/project/5d36c0f2ee8eac35ddeb27a1]]
     - Use Luke's Thesis
     - Use Dimitar's thesis
   - [ ] Titanium model fitting
     - Fitting data
     - Comparison beween d and sd models
     - Phonon spectra, heat data, phase information and stability.
     - Pure Titanium dislocations
* What, how, where, when, why?
* What
  Fitted canonical d titanium model such that we could have a better
  description of titanium within a tight-binding framework. Empirical
  potential are not accurate enough to describe the intricacies of the
  titanium structure.

* Fitting

  The d-band model of titanium was chosen to be of a simple form
  initially, from which one could build up complexity as and when.

  The overlap integrals were chosen to have a simple exponential
  distance dependence, as initially formulated by Ducastelle,
  cite:Ducastelle1970c and Allan cite:Allan1976. This form was
  originally motivated by an approximation to the density of states,
  of which the form was taken to be a Gaussian fitted to the
  second-moment of the distribution cite:Spanjaard1984. Extensions of
  pseudopotential theory to transition metals, by incorporating d-band
  resonances, suggest a fifth-degree power law distance dependence of
  the d-orbitals for transition metal matrix elements
  cite:Heine1980,Pettifor1995,Harrison1989. However, it has not been
  shown that a power-law dependence exhibits better transerability
  over a simple exponential dependence cite:Skinner1991,Paxton2010,
  in-fact, many power-law models have not fared well in predicting
  data outside of their fitting range
  cite:Paxton1987,Paxton1989. Transferability has been consistently
  shown for the iron tight-binding model created by Paxton and
  Elsässer cite:Paxton2010, which used an exponential
  dependence. Their model predicts data well outside of their fitting
  range: non-degenerate dislocation core structures found in the bcc
  phase cite:Simpsonb,Simpson2020, phonons and vacancy-formation
  energies. In addition, the Fe-Fe interactions have been shown
  suitable when incorporated with Fe-H/Fe-C interactions, to describe
  of hydrides and carbides cite:Paxton2010,Paxton2013.

  Canonical band theory cite:Andersen1985,Paxton2009a suggests that the bond integrals are in the
  ratio
  \[
  \label{eq:canonical_band_ratio}
  dd\sigma:  dd\pi:  dd\delta = -6:4:-1.
  \]
  These ratios are only applicable to the fifth-order power law
  dependence of the bond integrals, as there is no characteristic
  $d$-orbital radius from which to compare the ratios. It has been
  shown that non-orthogonal models of titanium, which have been
  subsequently orthogonalised to a $d$-band only model, have canonical
  ratios which deviate largely from canonical band theory; in the case
  of Urban /et al./ the ratio turned out to be $dd\sigma: dd\pi:
  dd\delta = -4.3 : 3.6 : -1$, in which the ordering of the ratio
  magnitudes changed cite:Urban2011.

  To obtain better fitting results, these ratios were allowed to vary
  from those found from canonical band theory. This is standard
  practice in other models . Non-orthogonal models
  of titanium, which have been subsequently orthogonalised to a
  $d$-band only model, have canonical ratios which deviate largely from
  canonical band theory; in the case of Urban /et al./ the ratio
  turned out to be $dd\sigma: dd\pi: dd\delta = -2.7 : 6.4 : -1$,
  in which the ordering of the ratio magnitudes changed
  cite:Urban2011. We do not allow the ratios to deviate by more than
  20% in our fitting.
  # WHY??-


  The bond integrals and pair potential ranges were chosen to start
  decaying to zero by a multiplicative polynomial between first and
  second neighbours in the hcp structure, going to zero between the
  second and third-neighbours. It was verified that the cutoffs were
  not very close to other neighbour shells in other titanium
  polymorphs, such that in future simulations, there would be no large
  and sudden forces arising from the inclusion of extra neighbours
  upon deformation. A multiplicative cutoff type was preferred over
  augmentative as it has been shown mitigate the effect of large
  second-derivatives, which would cause difficulty in replicating
  experimental elastic constants and phonon dispersion
  cite:Pashov2012.

  In fitting, it was found that having only first-neighbour
  interactions, did not give desirable properties for the hcp phase:
  elastic constants which resulted in negative Cauchy pressures and a
  poor description of the energy difference between titanium
  polymorphs. Increasing the range of the interactions to
  second-neighbours resulted in more favourable results.


  The form of the pair potential was chosen to be simple sum of two
  exponentials and a rapidly decaying power law. The exponentials,
  which have one large positive term, and a smaller negative term,
  contribute the most over the range of interaction, with the power
  law chosen to only increase the repulsion at smaller distances. The
  addition of this power law gave more desirable gamma surface
  energies more reminiscent of DFT. This will be discussed in section
  *SECTION LABEL*. The resultant pair potential was highly repulsive
  at short distances, yet became slightly
  attractive at larger distances. This allowed for one to approximately account for
  hybridisation effects in this simple $d$-orbital only model, as done
  in previous exclusively $d$-orbital tight-binding models for
  titanium cite:Girshick1998a.


  # Insert table for the parameters
     fdd=0.1958363809 qdds=0.5591275855 qddp=0.5690351902 qddd=0.7745947522 b0=58.0906936439 p0=1.2185323579 b1=-3.2299188646 p1=0.6862915307 b2=593519.1134129359 m2=-11.5000000000 p2=0.0000000000 ndt=2.0000000000 cr1=-6.0000000000 cr2=3.0474400934 cr3=-1.2317472193 r1dd=6.5000000000 rcdd=10.0000000000 rmaxhm=10.1000000000 npar=18

  # Insert figure for the bond integrals and the pair potential.

  # Insert figure for the bands compared to DFT

  # Insert figure for the table of properties.
  #+NAME: canonical_d_table.
   | Quantity  |   From Model |       Target |
   |-----------+--------------+--------------|
   | a_hcp     |   5.58523112 |   5.57678969 |
   | c/a       |   1.58371266 |   1.58731122 |
   | a_omega   |   8.93475285 |   8.73254342 |
   | c_omega   |   5.38726911 |   5.32343103 |
   | a_4h      |   5.57584691 |   5.56325146 |
   | c_4h      |  18.09810672 |  17.75908031 |
   | a_6h      |   5.57365569 |   5.54639384 |
   | c_6h      |  27.18378460 |  26.77136353 |
   | a_bcc     |   6.20079768 |   6.17948863 |
   | a_fcc     |   7.87290654 |   7.88677000 |
   | DE(o,h)   |   0.58764167 |  -0.63343333 |
   | DE(4h,h)  |   1.58019500 |   3.17160000 |
   | DE(6h,h)  |   2.48264833 |   3.72005000 |
   | DE(b,h)   |   5.35128500 |   7.63520000 |
   | DE(f,h)   |   3.78088500 |   4.51880000 |
   | c_11      | 171.60928873 | 176.10000000 |
   | c_33      | 198.90063708 | 190.50000000 |
   | c_44      |  47.42549704 |  50.80000000 |
   | c_12      |  94.65941969 |  86.90000000 |
   | c_13      |  61.22624060 |  68.30000000 |
   | M_freq_0  |   2.59341377 |   2.85858719 |
   | M_freq_1  |   2.59341378 |   2.85858719 |
   | M_freq_2  |   2.59341378 |   2.85858719 |
   | M_freq_3  |   2.59341379 |   2.85858719 |
   | M_freq_4  |   5.85272461 |   5.66706047 |
   | M_freq_5  |   5.85272461 |   5.66706047 |
   | H_freq_0  |   3.82320403 |   4.80643423 |
   | H_freq_1  |   3.82320403 |   5.58010025 |
   | H_freq_2  |   6.40288977 |   5.65316738 |
   | H_freq_3  |   6.40288977 |   6.36651842 |
   | H_freq_4  |   7.92857431 |   6.40050186 |
   | H_freq_5  |   7.92857431 |   7.64082373 |
   | bandw.  G |   3.69394702 |   5.87085872 |
   | bandw.  K |   4.65178817 |   4.97424321 |
   | bandw.  M |   5.19329495 |   7.78109872 |
   | bandw.  L |   4.21232412 |   6.34433701 |
   | bandw.  H |   3.54700549 |   9.70902614 |
   | DOSerr_h  |   0.00000000 |   0.00000000 |
   | DOSerr_o  |   0.00000000 |   0.00000000 |
   | E_pris_f  |  98.95340236 | 220.00000000 |



  # The motivaton behind this starting
  # point was such that one could use the work of Legrand
  # cite:Legrand1984 which exhibited dislocation core structures and
  # stacking fault energies which were more physical than previous
  # tight-binding models cite:Trinkle2006a.

  # To fit the canonical-d tight-binding model for titanium, we firstly
  # determined the region of parameter space in which


** Notes:                                                          :noexport:

*** Structure
    - What is the form of the bond integrals and why?
      - Bond integrals
      - Pair potential
	- Lack of embedding term for hybridisation, why?
	- Perhaps use Pettifor's argument for the addition of the
          attractive term in the pair potential as an argument for
          hybridisation?
	- This does not work for the form of the sd titanium model.
    - What is the fitting data?
      - Is this good data to use?
      - What is the motivation?
    - What algorithm was used to fit and why?



*** General Notes
   
    - The exponential bond integral comes from the density of states
      being assumed to be
    - Could the parameterisation be enhanced by environmentally-dependent
    bond integrals?

* sd fitting: Including hybridisation

  We included s orbitals such that one could more readily model the
  Ti$^{4+}$ oxidation state of the Ti ion, which would give a more
  physical representation of titanium ions in quantum electrochemistry
  calculations.
