#+TITLE: The effect of hydrogen atoms on the screw dislocation mobility in bcc iron A first-principles study
#+AUTHOR: Tigany Zarrouk
#+INTERLEAVE_PDF: /home/tigany/Documents/docs/Management/papers/Itakura et al. - 2013 - The effect of hydrogen atoms on the screw dislocation mobility in bcc iron A first-principles study.pdf

* Summary
  
  - Study mobility of screw dislocation in bcc Fe with DFT.
  - Show that /increase/ of screw dislocation velocity with a given temperature range. 
  - Interaction energy between hydrogen and screw core is calculated
    at various positions around dislocation line.
  - Results put into line tension model of curved dislocation to see
    effect that H has on dislocation migration.
  - /Softening/ effect of hydrogen caused by /reduction of kink nucleation enthalpy/.
  - /Hardening/ effect of hydrogen caused by /kink trapping/.
  - Transition between softening and hardening at lower critical temperature predicted.

* Notes
  
** Introduction
   - Solute softening sometimes occurs at low temperatures.
   - Solute atoms either:
     - Pin dislocations locally, hindering motion
     - /Reduce/ Peierls barrier locally, which:
       - Promotes /kink nucleation/
       - Thus /enhances/ dislocation motion.
   - Which effect is seen depends on core structure.

   - Hydrogen Embrittlement (HE) where fracture toughness is reduced
     with a lot of hydrogen, has mechanisms such as:
     - Hydrogen enhanced decohesion
     - Supression of dislocation emission by hydrogen
     - Hydrogen-enhanced localized plasticity. 
   /Which mechanism of hydrogen embrittlement is dominant under
   engineering conditions?/
   - H mechanism suggested due to:
     - Reduced flow stress
     - Increased screw dislocaton velocity with addition of H into bcc
       matrix.
   - H atoms concentrate in tensile regions.
   - If concentrated H atoms induce local slips, this causes increases in:
     - Local strain
     - Dislocation density
   - Mobility of dislocations is mediated in bcc metals by screw
     component as it has:
     - A large Peierls barrier
     - Slow migration

   - Edge dislocation strongly attracts H due to long ranged
     hydrostatic strain fields.
   - But due to already high mobility, the H atoms are more likely to /lower/
     the mobility under most conditions.
   - Mobility of the screw dislocation is mediated by the rate of
     atomic-scale kink nucleation.
   - A single H on a long screw dislocation segment can affect the
     /nucleation rate/ by lowering the /nucleation energy/.
     - This can explain friction measurements in iron. 
    
    
   - Two different configurations of dislocation core structrure:
     - Easy core (ECC) is most stable
     - Hard core (HCC) is metastable.
       - Larger free volume

   - Movement of a screw dislocation in any direction necessitates the
     alteration between ECC and HCC core structures.
   - This results in a large Peierls barrier.

   - As H atoms are attarcted to a free volume and lower the total
     energy, the trapping of a H atom in the HCC configuration is
     expected to be stronger than that for ECC.
   - The Peierls barrier would be /lower/ with hydrogen.


   - DFT calculations shwo that saddle point of migration path between
     two ECCs is close, but different to HCC.
   - Hard core and saddle point configuration (SPC) close to hard core energy.
  
   - Assumed here that the saddle point moves toward the HCC when a H
     atom is in its core.

   - H lowers Peierls barrier when H atom is just ahead of the screw
     dislocation in its slip plane.

   /Is average mobility of screw dislocation increased?/

   - For increased average movility at lease one H atom must always be
     close to adn ahead of a screw dislocation to promote kink-pair nucleation.
   - H atom just behind the screw disloation line can slow/stop the
     kink motion and /decrease/ dislocation mobility.

   
** DFT Calculation Details

   - VASP GGS with 350 eV cutoff
   - Relaxation tolerance 10meV/A
   - Green's Function Flexible boundary conditions with concentric hexagons.
     * Region 1 relaxed while region 2 fixed.
     * Green's Function relaxation
       + Each atom's displacement $\mathbf{u}_i$ relative to elastic
         solution is calculated
       + Large number of atoms added outside region 2, positions given
         by elastic solution.
       + Displacement fields in $\mathbf{u}_i$ in region 2 and outside
         so forces calculated by Hessian matrix $\mathbf{f}_i =
         \sum_{j \neq i} M_{ij}(\mathbf{u}_j-\mathbf{u}_i)$ are zero
       + /Minimum image convention/ applied for difference of
	 displacement to accound for periodicity of the lattice.
       + Atoms in region 1 are fixed for this step.
   - DFT and Greens function relaxation repeated until convergence.
   
   - Number of atoms in region 1 and 2 are 48 and 99 respectively.
   - Cartesian coordinates are parallel to:
     * X = $\langle \bar{2}11 \rangle$
     * Y = $\langle 0\bar{1}1 \rangle$
     * Z = $\langle 111 \rangle$
   - Z cell vector length is equal to burgers vector.
   
   - Uniform Ferromagnetic state is reproduced by GGA
   - Bulk properties calculated using 2 atom Fe cell.
     * $a = 2.833 A$

   - In dislocation simulations, initial magnetic moments are se to a
     uniform ferromagnetic state.
   - Initial magnetic moment of H is set to zero.
     * This is so it converges to the right stare regardless fo teh
       sign of the magnetic interaction between H and Fe.

   - After reference state obtained, H atom is placed at each
     tetrahedral site (t-site) near the core and the atomic
     configurations are relaxed for each case. 

   - Hydrogen solution energy:
     * $E_{s} = E_{d + H} - E_{d} - E_{H2}/2$
       + $E_{d + H}$: energy of dislocation and hydrogen. 
       + $E_{d}$: energy of reference dislocation. 
       + $E_{H2}$: energy of hydrogen molecule.
   
   - Binding energy $E_b$ is defined as difference in $E_s$ with
     respect to the bulk t-site solution energy. It is positive when
     $E_s$ is lower than that of the bulk t-site.

   - The zero-point energy correction to the solution energy is
     calculated from the Hessian matrix eigenvalues. (I assume the
     force constant matrix eigenvalues)
     * Assume that Fe atoms are heavy enough compared to H atoms that
       the ZP can be approximated by the motion of a single H atom.

     * Hessian calculated by displacing teh H atom in each of the $\pm
       X$, $\pm Y$, $\pm Z$ directions by $\pm 0.015 A$ and seeing the
       force calculated on the H atom.

   - ZPE correction calculated by equation $$ E_z = \frac{1}{2} \sum_{i=1}^{3} \frac{\hslash}{2\pi} \sqrt{ k_i / m_H } $$
     - $k_i$ are the three eigenvalues of the 3x3 Hessian matrix
     - $m_H$ is the mass of a H atom.
   
   - Errors are on the order of a few meV and are negligible.

   - Superscript Z denotes ZPE correction to energy.
     * $E^z_s =  E_{s} + E_{z} - E_{zH2}/2$
   - $E_{zH2} = 288 meV$ is the ZPE of a H$_2$ molecule.


   - Reference dislocation configuration repeated and 3 layers are
     stacked in the z direction to isolate H from its images.

   - 341 atoms in unfeasible in VASP but not all atoms necessary to
     calculate solution energy
     - Displacement of Fe atoms caused by hydrogen decays rapidly.
     - Hexagonal region of atoms centred on H in center is clipped out
       for calculation of binding energies.
     - Outer Fe atoms fixed to reference configuration
       * Because subjected to artificial forces from vaccuum region or
         domain boundary.
       * Domain boundary is more favourable as vaccuum region induces
         a large amount of charge redistribution and surface effects.
       * Domain boundary 3x3x8 k-points for high precision 1x1x8 elsewhere.
       * Numerical errors are 5 and 30 meV for each k-point config
         respectively.


   - To calculate required system size for E with small finite-size
     effects, $E_s$ calculated with 2$L^2$, with $L = 2,3,4$ with a H
     atom placed in the t-site.
   - Energies are close when unrelaxed, so /finite size effects come
     from relaxation mainly./
   - Finite size effects are inversely proportional to system size
   - Accuracy of 20 meV in solution energy of 188 meV.


   - 144 Fe atoms used in three layer calculation
     - 36 in core are relaxed
     - Rest are fixed in buffer region.
     - Width of buffer region results in forces on domain boundary on
       dynamic atoms to by 0.03 meV/A.
   - Finite size effect of cell estimated from t-site solution energy
     using same cell configuration.
   - Error from finite size is 27 meV
   - Total error from k-point sampling is 32 and 57 meV for the two
     different meshes respectively.
   - Errors from xc functional are not included and are around 85 meV
     per H atom.


   - Hydrogen binding to HCC expected to be larger than ECC.
   - H density in calculations is large and /ECC should transform to HCC to lower total energy by having favourable hydrogen binding at the cost of a higher core energy/.
   - To calculate H in dilute limit where the core structure is not affected by the high concentration of H:
     - Core position is fixed at half the thickness of the system away in the Z direction from the H atom.
     - Since core position related to Z displacement of three atoms surrounding the core, /core position at a certain layer can be fixed by prohibiting relaxation in Z/.
     - Thus dislocation core remains in reference configuration and the dilute concentration limit of $E_s$ is obtained. 


     
** Results
   
   - Both strong and weak binding sites for both hard and easy core.

*** ECC
   - ECC
   - $E_b^z = 256 \pm 32 meV$ for E2 site, E1 site is slightly lower
     in energy at 249 meV.
   - Strong sites E1 and E2 form basins of two of each in E2 E1 E1
     E2 structure near core.
   - Fe atoms around basin form slanted triangular prism with larger volume than the regular crystal. 
   - Broad basin predicted by EAM calculations as well. 

   - Equilibrium hydrogen concentration $C_b$ with binding energy $E^z_b$ is calculated from McLean's equation:

     \[ C_b = \frac{ C_0 \text{exp}( E^z_b / k_B T ) / 3 }{ 1 + \text{exp}( E^z_b / k_B T ) / 3 } \]

   - $C_0$ is the bulk hydrogen concentration.
   - Factor of 3 is for the three t-sites per Fe atom.

*** Concentration with McLean's Equation   
   - H-H interaction is neglected in quoted McLean's equation.
     - When attractive, H atoms attracted to binding sites with neighbour site that is already occupied by a H tom
     - The binding energy becomes larger than $E^z_b$.
     - Therefore ignoring the H-H interaction /underestimates/ concentration $C_b$.
   - When repulsive McLean's equation quoted is valid when $C_b < 0.5$
     - This is because the interaction is usually only limited to the neighboring H atoms. So $C_b$ is a lower bound. 

   
   - Can find the temperature dependence of $C_b$ at the E1/E2 basin with $C_0=0.1$. 
     
*** HCC

   - H0 at the center of the core is the strongest binding site at $390 \pm 32 meV$. 
   - This is 130 meV stronger than the ECC case.
   - /This indicates that a H atom can lower the Peierls barrier by about 130 meV/.
   - This is consistent with DFT calculations on difference between ECC and SPC ($~100 meV$).
   - Also implies that /ECC changes to HCC at expense of core energy./
   - If ECC changes to HCC when three E1/E2 basins are occupied with the same concentration $C_b$, H atoms in the three basins en up in the H0 site and two in the H2 sites.
   - Core energy increases by $40 meV/b$
   - Total hydrogen trap energy changes by 0 meV/b on average.
   - So the ECC will remain unchanged regardless of hydrogen concentration at the binding sites. 

   - The DFT data of distance dependence of binding energy of H to core can be fitted by a Lorentzian.

     \[ E_H(r) \frac{390}{1 + 2(r/r_0)^2} \text{meV} \]

   - $r_0 = \sqrt{6}a_0/3$ is the distance between two neighbouring ECC positions.

   - This Lorentzian agrees well with linear theory

   - Core distance $R_0$ seems to be around 2.5b. 



*** Line tension model 
    
    - To estimate the effect of H atoms on the kink-pair nucleation enthalpy and the kink nucleation rate, the interaction energy between the H atom and the screw dislocation is incorporated into a line tension model of a dislocation line.
    - This is expressed as an enthalpy of a curved screw dislocation configuration specified by the core positions $\mathbf{P}_j$ at each atomic layer $j$ of thickness $b$. 

      \[ E_{LT} = \frac{K}{2} \sum_j ( \mathbf{P}_j - \mathbf{P}_{j+1})^2 + \sum_j E_{\mathbf{P}_j}(\mathbf{P}_j) + \{ ( \sigma \cdot \mathbf{b} ) \times \mathbf{l}\} \cdot \mathbf{P}_j - \sum_{j,k} E_H( | \mathbf{P}_j - \mathbf{P}_{j+1} | )   \]

      - $K = 0.866 eV\AA^{-2}$ is a constant derived from the Hessian matrix of the ECC calculated from DFT (The other Itakura paper [[file:~/Documents/docs/Management/papers/itakura2012.pdf]])

	
    - $\mathbf{P}_j$ is a two dimensional vector whose components are the X and Y coordinates of the dislocation core position.
    - $E_P$ is the Peierls barrier per Burgers vectore $b$.
    - $E_H$ is the interaction energy between the dislocation line and the  atoms.
    - $\mathbf{P}_j^H$ is the position of the $k$th H atom in the XY plane.
    - Third term is the contributio from the external stress.
    - $\sigma \otimes b$ is the tensor-vector product of the stress and Burgers vector.
    - $\mathbf{l} = \mathbf{P}_j - \mathbf{P}_{j-1}$ 

    - Inclination of the dislocation line is given by $|= \mathbf{P}_j - \mathbf{P}_{j+1}|/b$ which is at most 1/30. 

    - Assume that the interactio between the disocation and the H atoms is described well by the hydrogen binding energy of a straight screw dislocation
      - This means the term $E_H$ is calculated only between a H atom and a representative dislocation segment which is closest to the H atom.
      - Also assume that the position of the H atom, which is initially in and E1/E2 basin, remains unchanged in the kink nucleation/migration process.
      - This is because the binding in this site is strong throughout the process. 
    


    

* Itakura 2012 First principles calculations of a screw dislocation in bcc iron

  
** Notes

   
*** Lattice Stress

    - Effect of applied stress is given by the Peach-Kohler term
      \[  \{  ( \sigma \otimes \mathbf{b}  ) \times \mathbf{l} \}\]
    - $\mathbf{l}$ is a vector parallel to the dislocation line and its length is equal to the length of the segment under consideration.
    - $\mathbf{r}$ is the dislocation positon. 

    - Additional effect on the shape of the Peierls energy $\delta E_P$ has been reported with applied stress. 

    - With anti-parallel burgers vectors, there is no contribution from the Peach-Kohler term, so we need another method to observe it. 

    - One can observe the forces on the two dislocatons $F_x$, $F_y$

    - Compare this to the lattice stress $S_x = -F_x / b^2 \pm \sigma_{YZ}$, $S_y = -F_y / b^2$ for the different strain cases and see if the Peierls potential is affected. 

      

*** Line tension Model
    
    - Dislocation mobility is determined by the formation enthalpy of a dislocation kink, a defect where the dislocation line moves from one energy minimun in the Peierls energy to the next.
    - The total dislocation enthalpy reaches a maximum when some part of the dislocation line overcomes the Peierls barrier.
    - Then a fully formed kink-pair moves in opposite directions, lowering the total enthalpy as they separate so the whole dislocation line moves along into the next Peierls valley. 
      [[file:~/Documents/docs/Management/Images/itakura_peierls_valley_kink_prop]]

    - Using line tension model / MD to obtain the kink-pair formation enthalpy reproduces dislocation velocity well. 
    - Screw dislocation has kink width of 10-20b
    - Direct calculation needs many slabs of atoms. (Thousands)
 
    
    \[ E_{LT} = \frac{K}{2} \sum_j ( \mathbf{P}_j - \mathbf{P}_{j+1})^2 + \sum_j \Delta \mathbf{P}_j + \{ ( \sigma \otimes \mathbf{b} ) \times \mathbf{l}\} \cdot \mathbf{P}_j    \]
    
    - Where $K$ is a constant related to the elastic constants of the material.
    - $j$ is an index of thin slabs with the thickness b parallel to the Z axis.
    - $\mathbf{P}_j = (P^x_j, P^y_j)$ is the position of a dislocation core in slab j.
    - $\Delta E_P$ is the Peierls barrier per Burgers vector b
      obtained in the previous section. 
    - the third term is the contribution from the external stress.


    - The constant K can be calculated by comparing the quadratic expansion of the line tension equation above in $(P^x_j, P^y_j)$ with the expansion of $E_d(x^d + \delta)$, which is given as 

      \[ E_d(x^d + \delta) - E_d(x^d) \approx -\sum_i \delta_i F_i + \frac{1}{2} \sum_{ij} H_{ij} \delta_i \delta_j    \]

    - The matrix $H_ij$ can be calculated by 
      \[ F_i(x^d + \delta) - F_i(x^d) = \sum_j H_{ij} \delta_j \]


    - To calculate K can demonstrate using EAM potential. 
      - Isolated easy core screw of 60$b$
      - Outermost atoms fixed to linear elasticity solutions
      - One atom in the innermost three atomic colums (I assume the triangle of the dislocation core) is displaced in the +Z direction by 0.01$\AA$.
      - Forces on every atom are calculated
      - Induced force on two atoms above and below are calculated to be $29 meV\AA^{-1}$ in Z direction.
      - On displaced atom it is $-82 meV\AA^{-1}$
      - Forces on other atoms are negligible.
      - Therefore $H_ii = 8.2 eV\AA^{-2}$ for the diagonal elements
      - $H_ij = -2.9 eV\AA^{-2}$ for the neighbouring pair on the same row
      - If denote Z as the displacement of the three innermost atoms on the layer $j$ by $z_{j,1}$, $z_{j,2}$, $z_{j,3}$, the total energy can be expanded as:

	\[ E_{\text{tot}} = \frac{1}{2}\sum_j\sum_{a=1,2,3} Az^2_{j,a} + K_0( z_{j,a} - z_{j-1,a} )^2  \]

      - $A = 2.4 ev\AA^{-1}$, $K_0 = 2.9 ev\AA^{-1}$

      - Using equation line tension equation above and

	\[ E_P(P^x_j, P^y_j) = E_d(x^d) = \min_{x^o} E_d(x^d, x^o) = E(x^d, \bar{x}^o(x^d))\]

	- Where $x^d$ denotes a set of degrees of freedom that is related to the dislocation position and is determined by $(P^x_j, P^y_j)$.
	- All other degrees of freedom are denoted by $x^o$.
	  
      - We can obtain $K = \frac{9}{32}K_0 = 0.816 ev\AA^{-2}$ for the Mendelev potential. 


	
    - The Peierls energy landscape of the same potential is calculated using a single layer isolated dislocation configuration and then fitted to the form of 

    \begin{align}
    E(\mathbf{r}) = 
    & \sum_{\alpha} [ C_1 f_e(  x_{\alpha}) + C_2 f_o(  x_{\alpha}) ] \\
    & \sum_{\alpha} [ C_3 f_e(2 x_{\alpha}) + C_4 f_o(2 x_{\alpha}) ] \\
    & \sum_{\alpha}   C_5 [ f_e(x_1 - x_2) + f_e(x_2 - x_3) + f_e(x_3 - x_1) ] \\
    \end{align}

    - Where the $C_i$ coefficients are fitted. 


    - Using this model a satisfactory shape of kinks is seen.
    - Kink pair energy using the MD gives 0.78 eV, line tension model gives 0.69 eV.
    - MD shows kink shape and energy is asymmetric between two types of kinks so there should be highre order terms of the gradient $( \mathbf{P}_j - \mathbf{P}_{j-1})$ in the energy
    - Errors of the line tension model can be attributed to it.
    - One can show that the kink formation energy is proportional to $\sqrt{KE_P}$,
      - So the uncertainty in $K$ only modestly affects the estimate of the kink formation energy. 

	
    - NOTE: Not sure if $K$ is the /compressibility/ or not.
      - $K = - \Delta V / P = 1/B$
	- $\Delta V = 1/3\text{Tr}(\varepsilon)$ is the dilatation
	- $P = 1/3\text{Tr}(\sigma)$ is the pressure
	- $B$ is the bulk modulus. 


* Ingredients for a KMC Model 

  1) Line tension model
     * 
  
* Questions

  - Why would H be likely to /lower/ the mobility of edge dislocations?
    
